version: '3'


services:


  #MySQL用コンテナ


  mysql:


    container_name: mysqll


    image: mysql:5.7


    volumes:


      - ./mysql:/var/lib/mysql


    ports:


      - 3306:3306


    environment:


      - MYSQL_ROOT_PASSWORD=root


      - MYSQL_DATABASE=user


      - MYSQL_USER=****


      - MYSQL_PASSWORD=****


  #phpMyAdmin用コンテナ


  phpmyadmin:


    container_name: phpMyAdminn


    depends_on:


      - mysql


    image: phpmyadmin/phpmyadmin


    environment:


      PMA_HOST: mysql


    restart: always


    ports:


      - "80:80"


  #php用コンテナ


  php:


    container_name: php-apachee


    build: ./php


    volumes:


      - ./html:/var/www/html


    ports:


      - 8080:80


    depends_on:


      - mysql